class Globals:

    running = True
    FRAMES_PER_SECOND = 30

    SCREEN_WIDTH = 1200
    SCREEN_HEIGHT = 800

    SCORE = 0

    # - Set the starting number of lives - #
    LIVES = 3

    

    money = 0

    # - Set the Window display name - #
    window_name = 'Dont take the bait!'

    # - Set the order of the rooms - #
    levels = ["WelcomeScreen", "GamePlay", "Mail", "End_game"]

    # - Set the starting level - #
    start_level = 0

    # - Set this number to the level you want to jump to when the game ends - #
    end_game_level = 4

    # - This variable keeps track of the room that will follow the current room - #
    # - Change this value to move through rooms in a non-sequential manner - #
    next_level = 0

    # - Change variable to True to exit the program - #
    exiting = False


# ############################################################# #
# ###### User Defined Global Variables below this line ######## #
# ############################################################# #

    response = None

    Email_decision = None

    total_count = 0
    destroyed_count = 0

    mail_messages_good = [
    "Welcome to BrightCo — How to finish setting up your new account",
    "Your order #3729 has shipped — Tracking QW123456789 (ETA Nov 20)",
    "Calendar invite: Product Roadmap Review — Tue, Nov 18 at 10:00 AM",
    "Invoice INV-2025-10 attached — Consulting services for October 2025",
    "Appointment confirmation: Dental check-up on 18 Nov at 14:30",
    "Greenway Farms — November newsletter and seasonal updates",
    "Confirmation: Password successfully changed for your account",
    "Please confirm your email address to complete registration",
    "You’re invited — BrightCity Charity Gala (RSVP by Dec 1)",
    "Receipt: Subscription renewal completed — Order #8942",
    "Shipping delay notice — Updated delivery window for order #2091",
    "Student Portal: Welcome packet and first-day checklist",
    "Refund processed — Credit to your card ending in 004 (3–5 business days)",
    "Quarterly team update — Goals, KPIs, and highlights",
    "Class cancellation: Today's 16:00 session has been cancelled",
    "Reservation confirmed — Lumen Bistro, 2 guests, Fri Nov 21 at 19:00",
    "Support ticket #4832 — Resolution summary and next steps",
    "Important: Changes to our privacy and cookie policy",
    "Volunteer orientation — Location, materials, and pre-reading",
    "Final agenda: Annual Conference — Download speakers & schedule",
    "Thank you for your donation — Impact summary and receipt",
    "Security notice — New device signed in to your account",
    "Parental Portal: How to set up your child’s profile",
    "Flight itinerary QF123 — Departure 25 Nov, Seat 14A",
    "Workshop materials and recording — 'Design Thinking Essentials'",
    "Enrollment confirmed — Intro to UX Design (Course ID: UX101)",
    "Scheduled maintenance: Service downtime Sun 02:00–04:00 AEST",
    "Password reset request — Use the verification code below",
    "Happy Birthday — Enjoy 15% off your next order (coupon attached)",
    "Performance review scheduled — Please prepare a 5-minute summary",
    "Product review request — Share feedback on your recent purchase",
    "HR update — Benefits enrollment window opens next Monday",
    "Community update — Photos from the new park opening ceremony",
    "Payroll advice — November payslip now available in Self Service",
    "Membership reactivated — Welcome back to BrightCo Rewards",
    "Assignment feedback posted — See comments in the student portal",
    "Office supplies order confirmation — ETA 4 business days",
    "Library hold ready for pickup — 'The Short Stories Collection'",
    "Invitation: Join our mobile app beta tester group",
    "Subscription cancellation confirmed — We're sorry to see you go",
    "In-store pickup ready — Order #8810 awaiting collection",
    "Monthly metrics report — Site traffic and conversion overview",
    "Congratulations — Fellowship program acceptance letter enclosed",
    "Reminder: Complete annual compliance training by Nov 30",
    "New comment on your blog post — Reply to continue the discussion",
    "Billing update — Payment method updated for account ending in 42",
    "Welcome to the neighborhood — Local resources & orientation guide",
    "Car service reminder — Oil change appointment Nov 20 at 09:00",
    "Press release: Company X launches new sustainability initiative",
    "Your event ticket — Download PDF and QR code for entry",
    "Onboarding feedback request — Help us improve the new user flow",
    "Course completion certificate — Congratulations and next steps",
    "LinkedIn connection request — Personalized note from Jane Doe",
    "Account statement — October 2025 (PDF attached)",
    "Webinar invitation: Designing for Accessibility — 3 Dec at 3pm AEDT",
    "Clinic follow-up — Please complete the post-visit questionnaire",
    "Library reminder — Items due in 3 days to avoid late fees",
    "Loyalty program activated — Start earning points today",
    "Professor message — Updated office hours and office location",
    "Project kickoff — Agenda and action items for Sprint 1",
    "Tech support update — Quick fix for intermittent connectivity",
    "Order confirmation — Your custom print is in production",
    "Privacy preferences updated — You will receive fewer marketing emails",
    "Scholarship awarded — Acceptance instructions and next steps",
    "Neighborhood watch meeting — Thursday, 7:00 PM at Community Hall",
    "Warranty registration complete — Model and serial recorded",
    "Community digest — Volunteer opportunities and upcoming events",
    "Seats filling fast — Course registration reminder for Term 1",
    "Donation receipt for tax records — Thank you for your support",
    "Product launch announcement — Features, specs, and pre-order links",
    "Hotel reservation confirmed — Check-in Nov 24 / Check-out Nov 27",
    "Weekly account activity summary — Last 7 days at a glance",
    "New hire orientation — First-day schedule and checklist",
    "Milestone update — Milestone 2 completed (sprint notes attached)",
    "Family photo day — Schedule your session and preparation tips",
    "Billing clarification — Explanation of recent charges on your account",
    "Reminder: Submit your timesheet by Friday 17:00",
    "Weather advisory & campus safety procedures — Please review",
    "Event RSVP confirmed — Thank you for registering",
    "Office celebration — Cake in the break room at 15:00 today",
    "Application status update — Your job application is under review",
    "New voicemail — Message from the front desk available to play",
    "Public transport update — Bus route changes starting next week",
    "Work anniversary — Congratulations on 1 year with AcmeCo",
    "Course materials available — Download reading pack for Week 1",
    "Maintenance completed — Elevator repairs finished today",
    "Customer survey — 3 quick questions to help improve service",
    "Team lunch postponed — New date to be confirmed next Friday",
    "Parent-teacher interviews — Book your preferred time slot",
    "Delivery confirmation — Order #7012 delivered today",
    "Mentor welcome — First steps and suggested reading for your program"
]

    mail_messages_bad = [
    "Your account has been locked. Verify your identity to restore access.",
    "Unusual login detected from a new device. Click here to secure your account.",
    "Congratulations! You’ve won a $500 Amazon gift card. Claim it now!",
    "Your payment to Netflix failed. Update your billing details here.",
    "We noticed suspicious activity on your bank account. Confirm details immediately.",
    "You have a pending package. Enter your address to schedule redelivery.",
    "Microsoft account alert: Password reset required.",
    "Final warning: Your Apple ID will be suspended in 24 hours.",
    "Your tax refund is ready to claim. Fill out this short form.",
    "Security update: Please verify your email credentials.",
    "Facebook: Someone tried to log in to your account. Confirm it was you.",
    "PayPal: Unauthorized charge detected. Review transaction.",
    "Your Gmail inbox is almost full. Free up space or upgrade storage now.",
    "You have a voicemail from your HR department. Listen here.",
    "Action required: Update your two-factor authentication settings.",
    "Delivery attempt failed. Click here to reschedule your parcel.",
    "Your university email will expire soon. Renew access.",
    "New job offer waiting. Submit your resume via the secure link.",
    "Your mobile service will be disconnected. Verify payment now.",
    "Outlook: You have unread encrypted messages. Sign in to view.",
    "You’ve been selected for a government relief payment. Confirm eligibility.",
    "Bank security alert: Multiple failed login attempts detected.",
    "Congratulations! Your loan has been approved. Accept funds here.",
    "Important document shared with you via Google Docs.",
    "Your subscription to Spotify Premium is about to end. Renew now.",
    "Your antivirus license has expired. Reactivate protection today.",
    "Final notice: Pending invoice from IT department.",
    "You missed a delivery from DHL. Re-enter your address to reschedule.",
    "Instagram: Verify your identity to keep your account active.",
    "Payment failed for your recent purchase. Update card info.",
    "Urgent: Account access temporarily suspended for verification.",
    "Crypto exchange alert: Withdraw request detected. Approve or deny.",
    "Your email password is expiring. Click to reset.",
    "Your Microsoft 365 license has been deactivated. Restore access.",
    "You’ve received a secure message from your doctor. View online.",
    "New message from school administration. Read immediately.",
    "Please confirm receipt of your COVID-19 relief payment.",
    "Apple: Suspicious activity found. Validate payment info.",
    "Bank of America: Your debit card is frozen. Verify to unlock.",
    "Final reminder: Pending toll fee balance. Pay to avoid penalty.",
    "Important payroll update. Confirm your employee ID.",
    "Your Steam account has been flagged for suspicious purchases.",
    "Tax department: Missing information in your recent filing.",
    "Action needed: Confirm your PayPal withdrawal request.",
    "Security alert: Sign-in from unfamiliar location detected.",
    "You have an unclaimed refund. Submit banking info to process.",
    "Dropbox: Storage almost full. Upgrade before access is limited.",
    "Congratulations! You’ve been selected for a free iPhone giveaway!",
    "Password change requested. If this wasn’t you, click here.",
    "Urgent: Confirm your account ownership to avoid closure.",
    "New message from your internet provider. Log in to view.",
    "Your credit score has changed. View your new report online.",
    "Urgent invoice from your supplier awaiting payment.",
    "We found a problem with your last transaction. Review details.",
    "Suspicious email login attempt. Review now.",
    "Click here to update your payment details for uninterrupted service.",
    "Office365: You’ve received an encrypted file from admin.",
    "FedEx: Unable to deliver your parcel. Provide updated address.",
    "Amazon Prime: Renew your membership today to keep benefits.",
    "You’ve received a digital gift card. Redeem within 24 hours.",
    "Your student account has been restricted. Re-verify credentials.",
    "Security update: Enable protection for your wallet.",
    "Account verification needed to maintain cloud access.",
    "HR: Important payroll correction needed. Submit details.",
    "Please verify your shipping information for your recent order.",
    "IT Support: Email upgrade scheduled. Confirm now.",
    "Your account has been flagged for unusual transactions.",
    "Google Drive: File shared with you. Click to open.",
    "Netflix: Subscription canceled due to billing issue.",
    "Claim your $100 fuel voucher before it expires!",
    "Urgent: Identity verification required to prevent suspension.",
    "Company notice: Policy update – please acknowledge receipt.",
    "Government alert: Your tax filing is incomplete.",
    "You’ve received a secure fax message. View attachment.",
    "We detected malware on your device. Scan immediately.",
    "Unpaid invoice #4572 due today. Pay now to avoid fees.",
    "Confirm your details to release your pending shipment.",
    "Security check: Verify your account within 12 hours.",
    "Urgent: Missing document from your HR file. Upload here.",
    "Please confirm your direct deposit information.",
    "Outlook security: Re-login required to maintain service.",
    "You’ve received an encrypted voicemail. Click to listen.",
    "Suspicious login from Chrome browser detected.",
    "Your delivery is on hold due to incorrect address.",
    "Your medical results are ready. Log in to view report.",
    "Bank notice: Temporary hold placed on your account.",
    "We’ve updated our privacy policy. Review and accept.",
    "Microsoft: Verify your credentials to keep your mailbox active.",
    "Action required: Update your payment method for recurring service.",
    "Urgent password reset request. Click below to proceed.",
    "You have a pending refund from your last purchase.",
    "PayPal: Review unusual login from a new country.",
    "Amazon: Problem with your recent order. Verify details.",
    "Dropbox: Your files will be deleted soon. Save them now.",
    "Security system update: Confirm your identity to continue.",
    "Account upgrade pending confirmation. Click here.",
    "You’ve received a secure PDF from accounting.",
    "New voicemail: Click here to listen.",
    "Confirm your phone number to secure your profile.",
    "Bank alert: Your card has been temporarily blocked.",
    "Your order is awaiting payment confirmation.",
    "Urgent: Verify your Apple Pay transaction immediately.",
    "Suspicious activity detected. Secure your login now.",
    "Your cloud backup failed. Reconnect your account."
]

    mail_messages_bad_R = [
    "Your account has been locked. Verify your identity to restore access.",
    "Unusual login detected from a new device. Click here to secure your account.",
    "Congratulations! You’ve won a $500 Amazon gift card. Claim it now!",
    "Your payment to Netflix failed. Update your billing details here.",
    "We noticed suspicious activity on your bank account. Confirm details immediately.",
    "You have a pending package. Enter your address to schedule redelivery.",
    "Microsoft account alert: Password reset required.",
    "Final warning: Your Apple ID will be suspended in 24 hours.",
    "Your tax refund is ready to claim. Fill out this short form.",
    "Security update: Please verify your email credentials.",
    "Facebook: Someone tried to log in to your account. Confirm it was you.",
    "PayPal: Unauthorized charge detected. Review transaction.",
    "Your Gmail inbox is almost full. Free up space or upgrade storage now.",
    "You have a voicemail from your HR department. Listen here.",
    "Action required: Update your two-factor authentication settings.",
    "Delivery attempt failed. Click here to reschedule your parcel.",
    "Your university email will expire soon. Renew access.",
    "New job offer waiting. Submit your resume via the secure link.",
    "Your mobile service will be disconnected. Verify payment now.",
    "Outlook: You have unread encrypted messages. Sign in to view.",
    "You’ve been selected for a government relief payment. Confirm eligibility.",
    "Bank security alert: Multiple failed login attempts detected.",
    "Congratulations! Your loan has been approved. Accept funds here.",
    "Important document shared with you via Google Docs.",
    "Your subscription to Spotify Premium is about to end. Renew now.",
    "Your antivirus license has expired. Reactivate protection today.",
    "Final notice: Pending invoice from IT department.",
    "You missed a delivery from DHL. Re-enter your address to reschedule.",
    "Instagram: Verify your identity to keep your account active.",
    "Payment failed for your recent purchase. Update card info.",
    "Urgent: Account access temporarily suspended for verification.",
    "Crypto exchange alert: Withdraw request detected. Approve or deny.",
    "Your email password is expiring. Click to reset.",
    "Your Microsoft 365 license has been deactivated. Restore access.",
    "You’ve received a secure message from your doctor. View online.",
    "New message from school administration. Read immediately.",
    "Please confirm receipt of your COVID-19 relief payment.",
    "Apple: Suspicious activity found. Validate payment info.",
    "Bank of America: Your debit card is frozen. Verify to unlock.",
    "Final reminder: Pending toll fee balance. Pay to avoid penalty.",
    "Important payroll update. Confirm your employee ID.",
    "Your Steam account has been flagged for suspicious purchases.",
    "Tax department: Missing information in your recent filing.",
    "Action needed: Confirm your PayPal withdrawal request.",
    "Security alert: Sign-in from unfamiliar location detected.",
    "You have an unclaimed refund. Submit banking info to process.",
    "Dropbox: Storage almost full. Upgrade before access is limited.",
    "Congratulations! You’ve been selected for a free iPhone giveaway!",
    "Password change requested. If this wasn’t you, click here.",
    "Urgent: Confirm your account ownership to avoid closure.",
    "New message from your internet provider. Log in to view.",
    "Your credit score has changed. View your new report online.",
    "Urgent invoice from your supplier awaiting payment.",
    "We found a problem with your last transaction. Review details.",
    "Suspicious email login attempt. Review now.",
    "Click here to update your payment details for uninterrupted service.",
    "Office365: You’ve received an encrypted file from admin.",
    "FedEx: Unable to deliver your parcel. Provide updated address.",
    "Amazon Prime: Renew your membership today to keep benefits.",
    "You’ve received a digital gift card. Redeem within 24 hours.",
    "Your student account has been restricted. Re-verify credentials.",
    "Security update: Enable protection for your wallet.",
    "Account verification needed to maintain cloud access.",
    "HR: Important payroll correction needed. Submit details.",
    "Please verify your shipping information for your recent order.",
    "IT Support: Email upgrade scheduled. Confirm now.",
    "Your account has been flagged for unusual transactions.",
    "Google Drive: File shared with you. Click to open.",
    "Netflix: Subscription canceled due to billing issue.",
    "Claim your $100 fuel voucher before it expires!",
    "Urgent: Identity verification required to prevent suspension.",
    "Company notice: Policy update – please acknowledge receipt.",
    "Government alert: Your tax filing is incomplete.",
    "You’ve received a secure fax message. View attachment.",
    "We detected malware on your device. Scan immediately.",
    "Unpaid invoice #4572 due today. Pay now to avoid fees.",
    "Confirm your details to release your pending shipment.",
    "Security check: Verify your account within 12 hours.",
    "Urgent: Missing document from your HR file. Upload here.",
    "Please confirm your direct deposit information.",
    "Outlook security: Re-login required to maintain service.",
    "You’ve received an encrypted voicemail. Click to listen.",
    "Suspicious login from Chrome browser detected.",
    "Your delivery is on hold due to incorrect address.",
    "Your medical results are ready. Log in to view report.",
    "Bank notice: Temporary hold placed on your account.",
    "We’ve updated our privacy policy. Review and accept.",
    "Microsoft: Verify your credentials to keep your mailbox active.",
    "Action required: Update your payment method for recurring service.",
    "Urgent password reset request. Click below to proceed.",
    "You have a pending refund from your last purchase.",
    "PayPal: Review unusual login from a new country.",
    "Amazon: Problem with your recent order. Verify details.",
    "Dropbox: Your files will be deleted soon. Save them now.",
    "Security system update: Confirm your identity to continue.",
    "Account upgrade pending confirmation. Click here.",
    "You’ve received a secure PDF from accounting.",
    "New voicemail: Click here to listen.",
    "Confirm your phone number to secure your profile.",
    "Bank alert: Your card has been temporarily blocked.",
    "Your order is awaiting payment confirmation.",
    "Urgent: Verify your Apple Pay transaction immediately.",
    "Suspicious activity detected. Secure your login now.",
    "Your cloud backup failed. Reconnect your account."
]

    mail_messages_good_R = [
    "Welcome to BrightCo — How to finish setting up your new account",
    "Your order #3729 has shipped — Tracking QW123456789 (ETA Nov 20)",
    "Calendar invite: Product Roadmap Review — Tue, Nov 18 at 10:00 AM",
    "Invoice INV-2025-10 attached — Consulting services for October 2025",
    "Appointment confirmation: Dental check-up on 18 Nov at 14:30",
    "Greenway Farms — November newsletter and seasonal updates",
    "Confirmation: Password successfully changed for your account",
    "Please confirm your email address to complete registration",
    "You’re invited — BrightCity Charity Gala (RSVP by Dec 1)",
    "Receipt: Subscription renewal completed — Order #8942",
    "Shipping delay notice — Updated delivery window for order #2091",
    "Student Portal: Welcome packet and first-day checklist",
    "Refund processed — Credit to your card ending in 004 (3–5 business days)",
    "Quarterly team update — Goals, KPIs, and highlights",
    "Class cancellation: Today's 16:00 session has been cancelled",
    "Reservation confirmed — Lumen Bistro, 2 guests, Fri Nov 21 at 19:00",
    "Support ticket #4832 — Resolution summary and next steps",
    "Important: Changes to our privacy and cookie policy",
    "Volunteer orientation — Location, materials, and pre-reading",
    "Final agenda: Annual Conference — Download speakers & schedule",
    "Thank you for your donation — Impact summary and receipt",
    "Security notice — New device signed in to your account",
    "Parental Portal: How to set up your child’s profile",
    "Flight itinerary QF123 — Departure 25 Nov, Seat 14A",
    "Workshop materials and recording — 'Design Thinking Essentials'",
    "Enrollment confirmed — Intro to UX Design (Course ID: UX101)",
    "Scheduled maintenance: Service downtime Sun 02:00–04:00 AEST",
    "Password reset request — Use the verification code below",
    "Happy Birthday — Enjoy 15% off your next order (coupon attached)",
    "Performance review scheduled — Please prepare a 5-minute summary",
    "Product review request — Share feedback on your recent purchase",
    "HR update — Benefits enrollment window opens next Monday",
    "Community update — Photos from the new park opening ceremony",
    "Payroll advice — November payslip now available in Self Service",
    "Membership reactivated — Welcome back to BrightCo Rewards",
    "Assignment feedback posted — See comments in the student portal",
    "Office supplies order confirmation — ETA 4 business days",
    "Library hold ready for pickup — 'The Short Stories Collection'",
    "Invitation: Join our mobile app beta tester group",
    "Subscription cancellation confirmed — We're sorry to see you go",
    "In-store pickup ready — Order #8810 awaiting collection",
    "Monthly metrics report — Site traffic and conversion overview",
    "Congratulations — Fellowship program acceptance letter enclosed",
    "Reminder: Complete annual compliance training by Nov 30",
    "New comment on your blog post — Reply to continue the discussion",
    "Billing update — Payment method updated for account ending in 42",
    "Welcome to the neighborhood — Local resources & orientation guide",
    "Car service reminder — Oil change appointment Nov 20 at 09:00",
    "Press release: Company X launches new sustainability initiative",
    "Your event ticket — Download PDF and QR code for entry",
    "Onboarding feedback request — Help us improve the new user flow",
    "Course completion certificate — Congratulations and next steps",
    "LinkedIn connection request — Personalized note from Jane Doe",
    "Account statement — October 2025 (PDF attached)",
    "Webinar invitation: Designing for Accessibility — 3 Dec at 3pm AEDT",
    "Clinic follow-up — Please complete the post-visit questionnaire",
    "Library reminder — Items due in 3 days to avoid late fees",
    "Loyalty program activated — Start earning points today",
    "Professor message — Updated office hours and office location",
    "Project kickoff — Agenda and action items for Sprint 1",
    "Tech support update — Quick fix for intermittent connectivity",
    "Order confirmation — Your custom print is in production",
    "Privacy preferences updated — You will receive fewer marketing emails",
    "Scholarship awarded — Acceptance instructions and next steps",
    "Neighborhood watch meeting — Thursday, 7:00 PM at Community Hall",
    "Warranty registration complete — Model and serial recorded",
    "Community digest — Volunteer opportunities and upcoming events",
    "Seats filling fast — Course registration reminder for Term 1",
    "Donation receipt for tax records — Thank you for your support",
    "Product launch announcement — Features, specs, and pre-order links",
    "Hotel reservation confirmed — Check-in Nov 24 / Check-out Nov 27",
    "Weekly account activity summary — Last 7 days at a glance",
    "New hire orientation — First-day schedule and checklist",
    "Milestone update — Milestone 2 completed (sprint notes attached)",
    "Family photo day — Schedule your session and preparation tips",
    "Billing clarification — Explanation of recent charges on your account",
    "Reminder: Submit your timesheet by Friday 17:00",
    "Weather advisory & campus safety procedures — Please review",
    "Event RSVP confirmed — Thank you for registering",
    "Office celebration — Cake in the break room at 15:00 today",
    "Application status update — Your job application is under review",
    "New voicemail — Message from the front desk available to play",
    "Public transport update — Bus route changes starting next week",
    "Work anniversary — Congratulations on 1 year with AcmeCo",
    "Course materials available — Download reading pack for Week 1",
    "Maintenance completed — Elevator repairs finished today",
    "Customer survey — 3 quick questions to help improve service",
    "Team lunch postponed — New date to be confirmed next Friday",
    "Parent-teacher interviews — Book your preferred time slot",
    "Delivery confirmation — Order #7012 delivered today",
    "Mentor welcome — First steps and suggested reading for your program"
]
    threshold = 999
